### ISSUE TITLE
External Volumes are missing in macOS 15.1

### ISSUE THREAD

**Issue by Tekl** [tempelmann/whatsopen#1]
I only see some internal Volumes in the Volumes selector on my MacBook Pro with macOS 15.1. I already gave the tool full disk access and enabled "get all users".

**Comment by tempelmann** [comment]
There are additional Privacy permissions in System Settings for external volumes, though. Have you checked that those also allow WhatsOpen? In my tests on 15.1b3 in a VM and WhatsOpen 4.0.1, it did see the external volumes without any prompting, so this may not be the issue. Which version of What's Open are you using?

Of course, it only lists volumes that have actually open files on them. If you external volumes are not access in any way, then they won't appear in the list nor in the "Volumes" popup menu. To test, create a .txt file and open it with BBEdit, for instance.

**Comment by Tekl** [comment]
After a reboot, I know also see the Volumes – even after removing full disk access. WhatsOpen 4.0.1 doesn't appear anymore under Files & Folders and there's no prompting in my case. So it seems to work as expected now. As the tool Sloth has seen access to the missing volumes, I thought there's a bug. Sorry, I had to restart before posting. I installed WhatsOpen freshly on my Mac.
